version: '3'

services:
  php:
    build: php
    volumes:
      - ./www:/var/www/html/
    depends_on:
      - db
    networks:
      - internal

  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/Back-end
      - ./Front-end:/var/www/html/Front-end
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - internal
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: super_user_name
      POSTGRES_PASSWORD: smth_smth
    volumes:
      - ./www/DB/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge