version: '3'
services:
  php:
    build: php
    ports:
     - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on: 
      - db
    networks:
      - internal
  nginx:
    build: nginx
    ports:
      - "smth"
    volumes:
      - ./www:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - internal
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: super_user_name
      POSTGRES_PASSWORD: smth_smth
      ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge