# Security
/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/activate:
  controller: Security
  action: activate

/forgot-password:
  controller: Security
  action: forgotPWD

/update-password:
  controller: Security
  action: updatePassword

# User
/home:
  controller: Home
  action: index

/about:
  controller: About
  action: index

/projects:
  controller: Projects
  action: index

/contact:
  controller: Contact
  action: index

/profile:
  controller: User
  action: show

# Admin
/home/settings:
  controller: Home
  action: settings

/about/settings:
  controller: About
  action: settings

/projects/settings:
  controller: Projects
  action: settings

/contact/settings:
  controller: Contact
  action: settings

/users:
  controller: User
  action: index

/comments:
  controller: Comment
  action: index

# Error
/404:
  controller: Error
  action: error404