# Controller Security
/:
  controller: Security
  action: login

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/activate:
  controller: Security
  action : activate

/forgot-password:
  controller: Security
  action: forgotPWD


# Controller Main -> Pour la vue du Frontend

/about:
  controller : Main
  action : loadView

/contact :
  controller : Main
  action : loadView

/home :
  controller : Main
  action : loadView

/projects :
  controller : Main
  action : loadView


#Controller Main -> Pour la vue du Backend

#pour admin seulement
/dashboard:
  controller : Main
  action : loadView

#pour utilisateur
/config :
  controller : Main
  action : loadView

/templates:
  controller : Main
  action : loadView

/comments:
  controller : Main
  action : loadView

/user_management:
  controller : Main
  action : loadView


#Gestion d'erreur

/error: