/:
  controller: Security
  action: login

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/forgot-password:
  controller: Security
  action: forgotPWD


/mypage:
  controller: Main
  action: home

/contact:
  controller : Main
  action : contact



/dashboard:
  controller : Main
  action : loadBackendView

/templates:
  controller : Main
  action : loadBackendView

/comments:
  controller : Main
  action : loadBackendView

/user_management:
  controller : Main
  action : loadBackendView



/error: