/:
  controller: Security
  action: login

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/forgot-password:
  controller: Security
  action: forgotPWD

/mypage:
  controller: Main
  action: home

/config:
  controller : Main
  action : config