/:
  controller: Main
  action: home

/config:
  controller : Main
  action :

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register