# Attention à vos noms de route (exemple de mauvaise route : forgotPassword) → pas de majuscule entre !

# Controller Security
/:
  controller: Security
  action: login

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/activate:
  controller: Security
  action : activate

/forgot-password:
  controller: Security
  action: forgotPWD

/update-password:
  controller : Security
  action : updatePassword


# Controller Main → Pour la vue du Frontend
#La fonction loadView → (/about → about = nom du fichier)

/about:
  controller : Main
  action : loadView

/contact :
  controller : Main
  action : loadView

/home :
  controller : Main
  action : loadView

/service :
  controller : Main
  action : loadView


#Controller Main -> Pour la vue du Backend
#La fonction loadView → (/dashboard → dashboard = nom du fichier)

#pour admin seulement
/dashboard:
  controller : Main
  action : loadView

#pour utilisateur
/config :
  controller : Main
  action : loadView

/templates:
  controller : Main
  action : loadView

/comments:
  controller : Main
  action : loadView

/user_management:
  controller : Main
  action : loadView


#Gestion d'erreur
/error: