/:
  controller: Security
  action: login

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/mypage:
  controller: Main
  action: home

/config:
  controller : Main
  action : config

/contact:
  controller : Main
  action : contact

/usermanagement:
  controller : Main
  action : usermanagement

/dashboard:
  controller : Main
  action : dashboard